export const JURISDICTIONS = [
  // ===== Countries =====
  { code: "US", name: "United States", type: "COUNTRY" },
  { code: "CA", name: "Canada", type: "COUNTRY" },

  // ===== United States (States + DC) =====
  { code: "US-AL", name: "Alabama", type: "STATE" },
  { code: "US-AK", name: "Alaska", type: "STATE" },
  { code: "US-AZ", name: "Arizona", type: "STATE" },
  { code: "US-AR", name: "Arkansas", type: "STATE" },
  { code: "US-CA", name: "California", type: "STATE" },
  { code: "US-CO", name: "Colorado", type: "STATE" },
  { code: "US-CT", name: "Connecticut", type: "STATE" },
  { code: "US-DE", name: "Delaware", type: "STATE" },
  { code: "US-FL", name: "Florida", type: "STATE" },
  { code: "US-GA", name: "Georgia", type: "STATE" },
  { code: "US-HI", name: "Hawaii", type: "STATE" },
  { code: "US-ID", name: "Idaho", type: "STATE" },
  { code: "US-IL", name: "Illinois", type: "STATE" },
  { code: "US-IN", name: "Indiana", type: "STATE" },
  { code: "US-IA", name: "Iowa", type: "STATE" },
  { code: "US-KS", name: "Kansas", type: "STATE" },
  { code: "US-KY", name: "Kentucky", type: "STATE" },
  { code: "US-LA", name: "Louisiana", type: "STATE" },
  { code: "US-ME", name: "Maine", type: "STATE" },
  { code: "US-MD", name: "Maryland", type: "STATE" },
  { code: "US-MA", name: "Massachusetts", type: "STATE" },
  { code: "US-MI", name: "Michigan", type: "STATE" },
  { code: "US-MN", name: "Minnesota", type: "STATE" },
  { code: "US-MS", name: "Mississippi", type: "STATE" },
  { code: "US-MO", name: "Missouri", type: "STATE" },
  { code: "US-MT", name: "Montana", type: "STATE" },
  { code: "US-NE", name: "Nebraska", type: "STATE" },
  { code: "US-NV", name: "Nevada", type: "STATE" },
  { code: "US-NH", name: "New Hampshire", type: "STATE" },
  { code: "US-NJ", name: "New Jersey", type: "STATE" },
  { code: "US-NM", name: "New Mexico", type: "STATE" },
  { code: "US-NY", name: "New York", type: "STATE" },
  { code: "US-NC", name: "North Carolina", type: "STATE" },
  { code: "US-ND", name: "North Dakota", type: "STATE" },
  { code: "US-OH", name: "Ohio", type: "STATE" },
  { code: "US-OK", name: "Oklahoma", type: "STATE" },
  { code: "US-OR", name: "Oregon", type: "STATE" },
  { code: "US-PA", name: "Pennsylvania", type: "STATE" },
  { code: "US-RI", name: "Rhode Island", type: "STATE" },
  { code: "US-SC", name: "South Carolina", type: "STATE" },
  { code: "US-SD", name: "South Dakota", type: "STATE" },
  { code: "US-TN", name: "Tennessee", type: "STATE" },
  { code: "US-TX", name: "Texas", type: "STATE" },
  { code: "US-UT", name: "Utah", type: "STATE" },
  { code: "US-VT", name: "Vermont", type: "STATE" },
  { code: "US-VA", name: "Virginia", type: "STATE" },
  { code: "US-WA", name: "Washington", type: "STATE" },
  { code: "US-WV", name: "West Virginia", type: "STATE" },
  { code: "US-WI", name: "Wisconsin", type: "STATE" },
  { code: "US-WY", name: "Wyoming", type: "STATE" },
  { code: "US-DC", name: "District of Columbia", type: "STATE" },

  // ===== Canada (Provinces + Territories) =====
  { code: "CA-AB", name: "Alberta", type: "PROVINCE" },
  { code: "CA-BC", name: "British Columbia", type: "PROVINCE" },
  { code: "CA-MB", name: "Manitoba", type: "PROVINCE" },
  { code: "CA-NB", name: "New Brunswick", type: "PROVINCE" },
  { code: "CA-NL", name: "Newfoundland and Labrador", type: "PROVINCE" },
  { code: "CA-NS", name: "Nova Scotia", type: "PROVINCE" },
  { code: "CA-ON", name: "Ontario", type: "PROVINCE" },
  { code: "CA-PE", name: "Prince Edward Island", type: "PROVINCE" },
  { code: "CA-QC", name: "Quebec", type: "PROVINCE" },
  { code: "CA-SK", name: "Saskatchewan", type: "PROVINCE" },
  { code: "CA-NT", name: "Northwest Territories", type: "TERRITORY" },
  { code: "CA-NU", name: "Nunavut", type: "TERRITORY" },
  { code: "CA-YT", name: "Yukon", type: "TERRITORY" }
] as const;
